<?php

namespace FantasyBundle\Repository;

/**
 * TalkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalkRepository extends \Doctrine\ORM\EntityRepository
{

	public function getByLeague($league)
	{
		$query = $this->createQueryBuilder('t')
			->where('t.league = :league')
			->setParameter('league', $league)
			->orderBy('t.created', 'DESC')
			->setMaxResults(30)
			->getQuery()
			->getResult()
		;

		return $query;
	}

}
