<?php

namespace PlayoffBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{


	// Retourne liste des joueurs pour tous ou une équipe précise ($id = all|id)
	public function getPlayers($id, $page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('p')
			->orderBy('p.name', 'ASC')
		;
		if($id != 'all'){
			$query
				->where('p.team = :idteam')
				->setParameter('idteam', $id)
			;
		}

		$query->getQuery();

		$query
			->setFirstResult( ($page-1) * $nbPerPage )
			->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function getPlayersByTeamWithoutPicks($t, $picks)
	{
		$query = $this->createQueryBuilder('p')
			->where('p.team IN (:teams)')
			->setparameter('teams', $t)
			->andWhere('p.id NOT IN(?1)')
			->setParameter(1,$picks)
			->getQuery()
			->getResult()
		;
		return $query;
	}

}
