<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLogs($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('l')
			->orderBy('l.created', 'DESC')
			->getQuery()
		;
		
		$query
			->setFirstResult( ($page-1) * $nbPerPage )
			->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

}
